# Owner of the GitHub repository
owner: SRESchool

# Name of the GitHub repository
repo: All-Jetexe-Websites-Uptime-Monitor

user-agent: pritesh-1904
skipReadme: true
skipDescription: true
skipTopics: true

# List of websites to monitor for uptime and SSL
sites:
  - name: Aiaviationacademy
    url: https://aiaviationacademy.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: aircrafto
    url: https://aircrafto.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Charterkings
    url: https://charterkings.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Executiveairrepair
    url: https://executiveairrepair.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Flighttrainingus
    url: https://flighttrainingus.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: flyaiaa
    url: https://flyaiaa.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Jetandrotor
    url: https://jetandrotor.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Jetexe
    url: https://jetexe.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: kitplanepart
    url: https://kitplanepart.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: learnflying
    url: https://learnflying.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Lightsportwest
    url: https://lightsportwest.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: pilotsdeal
    url: https://pilotsdeal.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: pegasus-estates
    url: https://pegasus-estates.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: pilotsindia
    url: https://pilotsindia.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Pilottrainingus
    url: https://pilottrainingus.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Planespart
    url: https://planespart.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Proezi
    url: https://proezi.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Buymlocal
    url: https://buymlocal.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
    port: 80, 443
    check: "tcp-ping"
    ipv6: true

status-website:
  cname: null
  baseUrl: /All-Jetexe-Websites-Uptime-Monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime/master/assets/logo.png
  name: All Jetexe Websites Uptime Monitor
  introTitle: Jetexe Websites Status
  introMessage: This page shows the uptime and SSL status of Jetexe Websites.
  favicon: https://raw.githubusercontent.com/upptime/upptime/master/assets/favicon.ico
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Workflow schedule (every 5 minutes)
workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
  ssl: "*/5 * * * *"

# Committer configuration
committer:
  name: Pritesh
  email: contact@motoshare.in

# Email notification configuration
notifications:
  - type: email
    smtpTo: contact@motoshare.in
    smtpFrom: contact@motoshare.in
    smtpHost: smtp.gmail.com
    smtpPort: 587
    smtpUsername: contact@motoshare.in
    smtpPassword: kmxg nshc vsrf kxqj

# Assignees for issues
assignees:
  - pritesh-1904
